project:
  type: website

website:
  title: "STATIO"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: About
      - text: Simuladores
        menu:
          - text: Estadística descriptiva
            href: categories/estadistica-descriptiva.qmd
          - text: Distribuciones
            href: categories/distribuciones.qmd
          - text: Estadística inferencial
            href: categories/estadistica-inferencial.qmd
          - text: Econometría
            href: categories/econometria.qmd
          - text: Investigación operativa
            href: categories/investigacion-operativa.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

